### PR TITLE
cleanup source and switch tests to JS

### PR DESCRIPTION
**Pull request by vsprintf**
Tests rewritten in JS to avoid coffeescript dependency.

Source had a few missing semicolons and trailing whitespace.

### CODE REVIEW

**Comment by wdavidw** [comment]
sorry but I wont accept it but i will take this opportunity to update this module. thank you. Strictly speaking, coffee is a dev dependency and not installed for common users.

**Comment by vsprintf** [comment]
Is there a specific reason to use coffee script just for the tests but not for the source?  Seems strange

**Comment by wdavidw** [comment]
yes, for the confort of my eyes: )

**Comment by wdavidw** [comment]
I just published a new version with your changes, thanks again

**Pull request closed without merging**
